export const GET_STUDENTS_LOADING = "GET_STUDENTS_LOADING";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";


export const GET_COLLEGES_LOADING = "GET_COLLEGES_LOADING";
export const GET_COLLEGES_SUCCESS = "GET_COLLEGES_SUCCESS";


export const ADD_STUDENT_LOADING = "ADD_STUDENT_LOADING";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS"; 

export const SHOW_RESULT = "SHOW_RESULT";

export const SORT_BY_PREFERENCE1 = "SORT_BY_PREFERENCE1";
export const SORT_BY_PREFERENCE2 = "SORT_BY_PREFERENCE2";
export const SORT_BY_PREFERENCE3 = "SORT_BY_PREFERENCE3";